In [45]:
import numpy as np
import pandas as pd

In [46]:
path = "../data"
train_data = pd.read_csv(path + "/train.csv", encoding="latin1")
train_data = pd.read_csv(path + "/test.csv", encoding="latin1")

In [47]:
train_data.head()

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0

In [48]:
print(train_data["text"][10])
train_data["sentiment"][10]

My bike was put on hold...should have known that.... argh total bummer

'negative'

In [49]:
train_data.shape

(4815, 9)

In [50]:
train_data.columns

Index(['textID', 'text', 'sentiment', 'Time of Tweet', 'Age of User',
       'Country', 'Population -2020', 'Land Area (Km²)', 'Density (P/Km²)'],
      dtype='str')

In [51]:
train_data = pd.concat((train_data["text"],train_data["sentiment"]),axis = 1)

In [52]:
train_data.head()

                                                text sentiment
0  Last session of the day  http://twitpic.com/67ezh   neutral
1   Shanghai is also really exciting (precisely -...  positive
2  Recession hit Veronique Branquinho, she has to...  negative
3                                        happy bday!  positive
4             http://twitpic.com/4w75p - I like it!!  positive

In [54]:
train_data = train_data[(train_data["sentiment"] == "positive") | (train_data["sentiment"] == "negative")]

In [55]:
train_data.shape

(2104, 2)

In [56]:
train_data["sentiment"].value_counts()

sentiment
positive    1103
negative    1001
Name: count, dtype: int64

In [57]:
train_data.isna().sum()

text         0
sentiment    0
dtype: int64

In [58]:
train_data.duplicated().sum()

np.int64(0)

In [63]:
sentiment_map = {"positive":1,
                 "negative":0}
x_train = np.array(train_data["text"])
y_train = np.array([sentiment_map[i] for i in train_data["sentiment"]])

In [64]:
y_train

array([1, 0, 1, ..., 0, 1, 1], shape=(2104,))

In [66]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

nltk.download("stopwords")
nltk.download('punkt')

/home/yousef-magdy/miniforge3/envs/dl/lib/python3.12/site-packages/nltk/downloader.py:1076: UserWarning: NLTK will not authorize the non-private download directory '/home/yousef-magdy/nltk_data': it (or an ancestor) is world- or group-writable, so another local user could plant files there. Choose a private location such as ~/nltk_data.
  for msg in self.incr_download(info_or_id, download_dir, force):
[nltk_data] Downloading package stopwords to /home/yousef-
[nltk_data]     magdy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/yousef-
[nltk_data]     magdy/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [69]:
def preprocess(sentence):
    stemer = PorterStemmer()
    sentence = sentence.lower()
    sentence = re.sub(r"http\S+", "", sentence)
    sentence = re.sub(r"<.*?>", "", sentence)
    sentence = re.sub(r"\s+", " ", sentence).strip()
    sentence = re.sub(r'[^\w\s]', '', sentence)

    sentence = word_tokenize(sentence)
    tokens=[]
    for word in sentence:
        if word not in stopwords.words("english"):
            word = stemer.stem(word)
            tokens.append(word)
    return " ".join(tokens)

In [71]:
print(x_train[5])
preprocess(x_train[5])

I THINK EVERYONE HATES ME ON HERE   lol

'think everyon hate lol'

In [72]:
for i,sentence in enumerate(x_train):
    x_train[i] = preprocess(sentence)

In [73]:
print(x_train[5])

think everyon hate lol

Counting vector Representation

In [ ]:
word_vec = np.zeros(3)

array([0., 0., 0.])